server:
  port: 8080
spring:
  application:
    name: platform-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: platform-user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**,/auth/** # protected
        - id: platform-notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/notifications/**   # protected
security:
    jwt:
      secret: "HrIiHp1aql+FNsQ+4KGTs4Co4ayc8tcEgXZpzRKvR51sDLRsGXbysLriPUlcEtIHc21kflfOlIHF2I+yw0OgdQ=="
      issuer:
      audience:
      roles-claim: roles
      username-claim: username
      user-id-source: sub     
